### PR TITLE
Implemented activity buttons. Aesthetic changes to activity

### PR DESCRIPTION
**Pull request by PedroFalcao**
Implemented AttributeScreenActivity buttons. Aesthetic changes to attribute activity.

---

This change is [Reviewable](https://reviewable.io/reviews/lurian/miguxada/5)

### CODE REVIEW

**Comment by Lurian** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

_[app/build.gradle, line 37 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ04xRaem0MJy4PdUB:-KPQ04xRaem0MJy4PdUC:b-o90bna) ([raw file](https://github.com/lurian/miguxada/blob/03fba93b2e2a6dd9b317491c23f9f72fed599b25/app/build.gradle#L37)):_

> ``` Gradle
> dependencies {
> 
>   compile "com.android.support:appcompat-v7:22.0.0+"
> ```

removeu pq?

---

_[app/src/main/java/com/example/android/app/AttributeScreenActivity.java, line 4 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ0EiU8MKIRvglHZ7A:-KPQ0EiU8MKIRvglHZ7B:b3vgx14) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/app/src/main/java/com/example/android/app/AttributeScreenActivity.java#L4)):_

> import android.os.Handler;
>  lembrar de remover imports nao utilizados

---

_[app/src/main/java/com/example/android/app/AttributeScreenActivity.java, line 37 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ0YJ7XnM1P3otzpFr:-KPQ0YJ7XnM1P3otzpFs:b-h5ll6g) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/app/src/main/java/com/example/android/app/AttributeScreenActivity.java#L37)):_

>    @Override
>     public void onClick(View view) {
> 
> Faz isso daqui funcionar com o binding. Mas lembrar que existem listener especificos que evitam esse verbose de código aqui. Olhar API de listeners de data binding. 

Nao tenho ctz do que eles fazem, mas da uma estudada e verifica a possibilidade.

---

_[app/src/main/java/com/example/android/app/AttributeScreenActivity.java, line 79 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ0mc3HMdGrhY6Bem2:-KPQ0mc3HMdGrhY6Bem3:b4iv7cg) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/app/src/main/java/com/example/android/app/AttributeScreenActivity.java#L79)):_

> ``` Java
>     }
> 
>     private void instantiateButtons() {
> ```

documentacao

---

_[app/src/main/java/com/example/model/character/attribute/Attribute.java, line 28 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ0rfnpOfnfBqgGnKY:-KPQ0rfnpOfnfBqgGnKZ:b2yhabb) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/app/src/main/java/com/example/model/character/attribute/Attribute.java#L28)):_

> ``` Java
> 
>     public void setValue(Long value) {
>         notifyPropertyChanged(BR.value);
> ```

coloca esse notify depois da mudanca de valor. Faz o mesmo em Status.

Acho estranho vc notificar a mudanca de um valor antes desse valor ser modificado, funciona... mas mesmo assim...

---

_[app/src/main/java/com/example/model/character/status/Status.java, line 95 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ12ulnDnys-u5Hbox:-KPQ12ulnDnys-u5Hboy:b-s96z8p) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/app/src/main/java/com/example/model/character/status/Status.java#L95)):_

> ```
>     notifyPropertyChanged(BR.max);
>     this.max = max;
> ```
> 
> mesmo que falei sobre a ordem

---

_[gradle/wrapper/gradle-wrapper.properties, line 1 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ1_O8JrDq82T7yO8Z:-KPQ1_O8JrDq82T7yO8_:b-ssvl5r) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/gradle/wrapper/gradle-wrapper.properties#L1)):_

> Wed Aug 17 19:47:45 GFT 2016
> pq que isso mudou? Deveria ter mudado?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by Lurian** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by PedroFalcao** [comment]
_[app/build.gradle, line 37 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ04xRaem0MJy4PdUB:-KPQ2PdrALkvKITZgJNC:beckba9) ([raw file](https://github.com/lurian/miguxada/blob/03fba93b2e2a6dd9b317491c23f9f72fed599b25/app/build.gradle#L37)):_
<details><summary>

<i>Previously, Lurian (Lucas Ribeiro de Andrade) wrote…</i></summary>



> removeu pq?
> </details>
> duplicado. Olha o trecho logo abaixo

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by PedroFalcao** [comment]
_[gradle/wrapper/gradle-wrapper.properties, line 1 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/5#-KPQ1_O8JrDq82T7yO8Z:-KPQ4FvW4nTaBKm05nlx:bfy2wpe) ([raw file](https://github.com/lurian/miguxada/blob/254ceee3ee809f4abe7c5e9dc03c0012952b5338/gradle/wrapper/gradle-wrapper.properties#L1)):_
<details><summary>

<i>Previously, Lurian (Lucas Ribeiro de Andrade) wrote…</i></summary>



> > Wed Aug 17 19:47:45 GFT 2016
> > pq que isso mudou? Deveria ter mudado?
> > </details>
> > não mexi nisso, acho que foi o android studio

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by Lurian** [comment]
Reviewed 3 of 7 files at r2.
Review status: 6 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by Lurian** [comment]
Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Comment by Lurian** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/5)_

**Pull request merged**
