### PR TITLE
Eliminated blank lines

### PR DESCRIPTION
**Pull request by PedroFalcao**
This change is [Reviewable](https://reviewable.io/reviews/lurian/miguxada/2)

### CODE REVIEW

**Comment by Lurian** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[app/src/main/java/com/example/android/app/StatusScreen.java, line 5 [r1]](https://reviewable.io:443/reviews/lurian/miguxada/2#-KOvXTFh9Z9yHytoqJuL:-KOvXTFh9Z9yHytoqJuM:b6pwwff) ([raw file](https://github.com/lurian/miguxada/blob/892c4004ef7c200c03ec4e57808312ab551f68ad/app/src/main/java/com/example/android/app/StatusScreen.java#L5)):_

>  
>  
> import android.os.Bundle;
> import android.widget.TextView;
>  
> Opa, bela correcao

---

_[app/src/main/java/com/example/model/character/attribute/Attribute.java, line 10 [r2]](https://reviewable.io:443/reviews/lurian/miguxada/2#-KOvXMEYSS2_9PLIHyLX:-KOvXMEYSS2_9PLIHyLY:b-2zvqwx) ([raw file](https://github.com/lurian/miguxada/blob/6740fa0037869923ad102030ed5cf9b1ddd0f4e1/app/src/main/java/com/example/model/character/attribute/Attribute.java#L10)):_

> ``` Java
> public abstract class Attribute {
> 
>     /** Value of the attribute **/
> ```

Current Value of the attribute

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/2)_

**Comment by PedroFalcao** [comment]
_[app/src/main/java/com/example/model/character/attribute/Attribute.java, line 10 [r2]](https://reviewable.io:443/reviews/lurian/miguxada/2#-KOvXMEYSS2_9PLIHyLX:-KOvYLpjaw65JTuULkTG:bt2vr1b) ([raw file](https://github.com/lurian/miguxada/blob/6740fa0037869923ad102030ed5cf9b1ddd0f4e1/app/src/main/java/com/example/model/character/attribute/Attribute.java#L10)):_
<details><summary>

<i>Previously, Lurian (Lucas Ribeiro de Andrade) wrote…</i></summary>



> Current Value of the attribute
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/2)_

**Comment by Lurian** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/2)_

**Comment by PedroFalcao** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/lurian/miguxada/2)_

**Pull request merged**
